import { Link } from "../router";
import { learnArticles } from "../data/learnArticles";
import { GITHUB_URL, SiteLayout } from "../components/site/SiteLayout";
import { Seo } from "../components/site/Seo";

const coverage = [
  ["Severe weather", "Official alerts, forecast outlooks, observations, and tropical cyclone information.", "weather-alerts"],
  ["Earthquakes", "Recent earthquake catalogs and available shaking context from public seismic networks.", "earthquakes"],
  ["Wildfires", "Reported fire incidents, fire-weather outlooks, and related environmental signals.", "wildfires"],
  ["Flooding and water", "Flood alerts, river gauges, coastal conditions, and model-based river signals.", "floods"],
  ["Environmental conditions", "Air quality, drought, volcano, marine, and space-weather observations.", "alert-severity"],
  ["Disaster context", "Disaster declarations, global disaster feeds, and historical storm records.", "using-openriskradar"],
] as const;

const websiteData = [
  { "@context": "https://schema.org", "@type": "WebSite", name: "OpenRisk Radar", url: "https://openriskradar.com/", description: "An open-source public risk and hazard situational-awareness website." },
  { "@context": "https://schema.org", "@type": "SoftwareApplication", name: "OpenRisk Radar", applicationCategory: "UtilitiesApplication", operatingSystem: "Web", url: "https://openriskradar.com/app", isAccessibleForFree: true },
];

export function HomePage() {
  return <SiteLayout>
    <Seo path="/" title="OpenRisk Radar | Live Public Risk and Hazard Alerts" description="Explore trusted public hazard feeds in a privacy-conscious dashboard and learn how to interpret weather, earthquake, wildfire, and flood information." structuredData={websiteData} />
    <section className="home-hero"><div className="site-container hero-grid"><div><p className="eyebrow">Open-source situational awareness</p><h1>See emerging risks in one place</h1><p className="hero-copy">OpenRisk Radar brings together trusted public alerts and observations for severe weather, wildfires, earthquakes, floods, environmental conditions, and other hazards in one interactive, privacy-conscious dashboard—with optional background monitoring for saved places.</p><div className="button-row"><Link to="/app" className="button">Open Live Radar</Link><Link to="/methodology" className="button button-secondary">How It Works</Link></div><p className="hero-caveat">Informational only. Official emergency instructions always take priority.</p></div><DashboardPreview /></div></section>
    <section className="section"><div className="site-container"><div className="section-heading"><p className="eyebrow">Coverage</p><h2>Public signals, organized around a place</h2><p>Coverage reflects feeds implemented in the current application. Availability and detail vary by location and provider.</p></div><div className="card-grid coverage-grid">{coverage.map(([title, text, slug]) => <article className="feature-card" key={title}><span className="card-signal" aria-hidden="true" /><h3>{title}</h3><p>{text}</p><div className="card-links"><Link to="/app">View radar</Link><Link to={`/learn/${slug}`}>Learn more</Link></div></article>)}</div></div></section>
    <section className="section section-tint"><div className="site-container"><div className="section-heading"><p className="eyebrow">Method</p><h2>How it works</h2></div><ol className="steps"><li><span>01</span><h3>Collect public feeds</h3><p>Request records from government, scientific, and openly available providers.</p></li><li><span>02</span><h3>Normalize events</h3><p>Map varied source records into common categories, timing, geometry, and severity fields.</p></li><li><span>03</span><h3>Present one interface</h3><p>Combine map, feed, filters, saved places, and source details in one searchable view.</p></li><li><span>04</span><h3>Monitor by choice</h3><p>Recheck explicitly enabled places in the background and offer controlled browser notifications.</p></li></ol></div></section>
    <section className="section"><div className="site-container split-section"><div><p className="eyebrow">Designed for context</p><h2>Useful across many monitoring needs</h2><p>Travelers, risk teams, emergency planners, journalists, researchers, homeowners, and people monitoring family or property can use OpenRisk Radar as one input to broader situational awareness.</p><p>It does not independently verify each event, predict emergencies, or replace professional and official services.</p></div><div className="principles"><div><strong>No account required</strong><span>Search and explore without creating a profile.</span></div><div><strong>Monitoring is opt-in</strong><span>Saved places stay on your device unless you explicitly enable background checks.</span></div><div><strong>Source-forward</strong><span>Attribution and original records stay visible.</span></div><div><strong>Open source</strong><span>Methods and implementation can be inspected on GitHub.</span></div></div></div></section>
    <section className="section section-dark"><div className="site-container"><div className="section-heading"><p className="eyebrow">Learning center</p><h2>Understand the signal before acting on it</h2><p>Plain-language guides explain alert terminology, data limits, and how to read what the map shows.</p></div><div className="article-grid">{learnArticles.slice(0, 3).map((article) => <article className="article-card" key={article.slug}><p className="article-meta">{article.category} · {article.readingTime}</p><h3><Link to={`/learn/${article.slug}`}>{article.title}</Link></h3><p>{article.description}</p><Link to={`/learn/${article.slug}`} className="text-link">Read guide <span aria-hidden="true">→</span></Link></article>)}</div><div className="section-action"><Link to="/learn" className="button button-light">Explore all guides</Link></div></div></section>
    <section className="section"><div className="site-container transparency"><div><p className="eyebrow">Data transparency</p><h2>Every feed has limits</h2><p>OpenRisk Radar uses public or openly available sources and preserves attribution. Refresh intervals differ. Events and optional notifications can be delayed, incomplete, duplicated, unavailable, or later revised. The platform is informational, not an official or guaranteed emergency notification service.</p></div><div className="link-panel"><Link to="/data-sources">Review every data source</Link><Link to="/methodology">Read the methodology</Link><Link to="/privacy">Understand browser data use</Link><a href={GITHUB_URL} target="_blank" rel="noreferrer">Inspect the source code</a></div></div></section>
    <section className="final-cta"><div className="site-container"><h2>Understand what is happening around you.</h2><p>Start with a location and inspect the public records behind every signal.</p><Link to="/app" className="button button-light">Open Live Radar</Link></div></section>
  </SiteLayout>;
}

function DashboardPreview() {
  return <div className="dashboard-preview" role="img" aria-label="Illustrated preview of the OpenRisk Radar map, event feed, and risk summary"><div className="preview-top"><span>OpenRisk Radar</span><span className="preview-search">Search a place</span></div><div className="preview-body"><div className="preview-map"><span className="radar-ring ring-one"/><span className="radar-ring ring-two"/><i className="map-dot dot-one"/><i className="map-dot dot-two"/><i className="map-dot dot-three"/></div><div className="preview-panel"><strong>Situation summary</strong><span/><span/><span className="short"/><strong>Public feed</strong><span/><span/><span/></div></div></div>;
}
